# <Prefix> = Ctrl+a (instead of Ctrl+b)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Config reload (Prefix + r)
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
