#!/bin/bash

echo "Installing oh-my-zsh plugins..."

ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

mkdir -p "$ZSH_CUSTOM/plugins"

install_plugin() {
  local repo="$1"
  local name="$2"
  local dir="$ZSH_CUSTOM/plugins/$name"

  if [[ ! -d "$dir" ]]; then
    echo "Installing $name..."
    git clone --depth=1 "$repo" "$dir"
    echo "$name installed"
  else
    echo "$name already installed"
  fi
}

install_plugin "https://github.com/zsh-users/zsh-syntax-highlighting.git" "zsh-syntax-highlighting"
install_plugin "https://github.com/zsh-users/zsh-autosuggestions" "zsh-autosuggestions"
install_plugin "https://github.com/unixorn/fzf-zsh-plugin.git" "fzf-zsh-plugin"

echo "oh-my-zsh plugins installation complete!"
