source-file ~/.config/tmux/conf.d/10-options.conf
source-file ~/.config/tmux/conf.d/20-bindings.conf
source-file ~/.config/tmux/conf.d/30-panes.conf
source-file ~/.config/tmux/conf.d/40-windows.conf
source-file ~/.config/tmux/conf.d/50-sessions.conf
